// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ConferenceDocumentDataSlicesSlice = never;

/**
 * Content for Conference documents
 */
interface ConferenceDocumentData {
  /**
   * Name field in *Conference*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: conference.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Image field in *Conference*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: conference.image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<"main">;

  /**
   * Description field in *Conference*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: conference.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Date defined field in *Conference*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: conference.date_defined
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  date_defined: prismic.BooleanField;

  /**
   * Date field in *Conference*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: conference.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Subscribe field in *Conference*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: conference.subscribe
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  subscribe: prismic.LinkField;

  /**
   * Theme field in *Conference*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: Red
   * - **API ID Path**: conference.theme
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  theme: prismic.SelectField<
    "Red" | "Pink" | "Blue" | "Green" | "Yellow" | "White",
    "filled"
  >;

  /**
   * Available field in *Conference*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: conference.available
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  available: prismic.BooleanField;

  /**
   * Slice Zone field in *Conference*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: conference.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ConferenceDocumentDataSlicesSlice>;
}

/**
 * Conference document from Prismic
 *
 * - **API ID**: `conference`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ConferenceDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ConferenceDocumentData>,
    "conference",
    Lang
  >;

type HomeDocumentDataSlicesSlice = CallToActionSlice | RelationshipSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Keywords field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_keywords
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_keywords: prismic.KeyTextField;

  /**
   * Title field in *Home*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: home.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *Home*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: home.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Logo field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice>
  /**
   * Navigation field in *Home*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: home.navigation
   * - **Tab**: Customization
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */;
  navigation: prismic.BooleanField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<HomeDocumentData>, "home", Lang>;

/**
 * Item in *Navigation → Links*
 */
export interface NavigationDocumentDataLinksItem {
  /**
   * Label field in *Navigation → Links*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Optional - Label for the link
   * - **API ID Path**: navigation.links[].label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  label: prismic.TitleField;

  /**
   * Link field in *Navigation → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link for navigation item
   * - **API ID Path**: navigation.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Navigation documents
 */
interface NavigationDocumentData {
  /**
   * Links field in *Navigation*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: navigation.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<NavigationDocumentDataLinksItem>>;
}

/**
 * Navigation document from Prismic
 *
 * - **API ID**: `navigation`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type NavigationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<NavigationDocumentData>,
    "navigation",
    Lang
  >;

type PageDocumentDataSlicesSlice = FaqSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Title field in *Page*
   *
   * - **Field Type**: Title
   * - **Placeholder**: Title for the page
   * - **API ID Path**: page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: page.content
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice>;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Social*
 */
export interface SettingsDocumentDataSocialItem {
  /**
   * Label field in *Settings → Social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Accesibility field in *Settings → Social*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social[].a11y
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  a11y: prismic.KeyTextField;

  /**
   * href field in *Settings → Social*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social[].href
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  href: prismic.LinkField;

  /**
   * Show field in *Settings → Social*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: settings.social[].show
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  show: prismic.BooleanField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Title field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.title
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Description field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.description
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Corporate name field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.corporate_name
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  corporate_name: prismic.KeyTextField;

  /**
   * CNPJ field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.cnpj
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cnpj: prismic.KeyTextField;

  /**
   * E-mail field in *Settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Data
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  email: prismic.KeyTextField
  /**
   * Logo Full field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo_full
   * - **Tab**: Customization
   * - **Documentation**: https://prismic.io/docs/field#image
   */;
  logo_full: prismic.ImageField<never>;

  /**
   * Logo Short field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo_short
   * - **Tab**: Customization
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo_short: prismic.ImageField<never>
  /**
   * Social field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.social[]
   * - **Tab**: Social
   * - **Documentation**: https://prismic.io/docs/field#group
   */;
  social: prismic.GroupField<Simplify<SettingsDocumentDataSocialItem>>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

/**
 * Content for Sponsor documents
 */
interface SponsorDocumentData {
  /**
   * Name field in *Sponsor*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  name: prismic.TitleField;

  /**
   * Url field in *Sponsor*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField;

  /**
   * Description field in *Sponsor*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Logo field in *Sponsor*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<"highlight" | "small">;

  /**
   * Start field in *Sponsor*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.date_start
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_start: prismic.DateField;

  /**
   * End field in *Sponsor*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.date_end
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date_end: prismic.DateField;

  /**
   * Type field in *Sponsor*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.sponsorship_type
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  sponsorship_type: prismic.SelectField<
    "Platinum" | "Gold" | "Silver" | "Bronze"
  >;

  /**
   * Highlight field in *Sponsor*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: sponsor.highlight_video
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  highlight_video: prismic.EmbedField;
}

/**
 * Sponsor document from Prismic
 *
 * - **API ID**: `sponsor`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SponsorDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<SponsorDocumentData>,
    "sponsor",
    Lang
  >;

export type AllDocumentTypes =
  | ConferenceDocument
  | HomeDocument
  | NavigationDocument
  | PageDocument
  | SettingsDocument
  | SponsorDocument;

/**
 * Primary content in *CallToAction → Primary*
 */
export interface CallToActionSliceDefaultPrimary {
  /**
   * Title field in *CallToAction → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: This is where it all begins...
   * - **API ID Path**: call_to_action.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *CallToAction → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *CallToAction → Items*
 */
export interface CallToActionSliceDefaultItem {
  /**
   * Title field in *CallToAction → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Link Label field in *CallToAction → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].link_label
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  link_label: prismic.RichTextField;

  /**
   * Link field in *CallToAction → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: call_to_action.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Default variation for CallToAction Slice
 *
 * - **API ID**: `default`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CallToActionSliceDefaultPrimary>,
  Simplify<CallToActionSliceDefaultItem>
>;

/**
 * Slice variation for *CallToAction*
 */
type CallToActionSliceVariation = CallToActionSliceDefault;

/**
 * CallToAction Shared Slice
 *
 * - **API ID**: `call_to_action`
 * - **Description**: CallToAction
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CallToActionSlice = prismic.SharedSlice<
  "call_to_action",
  CallToActionSliceVariation
>;

/**
 * Primary content in *Faq → Primary*
 */
export interface FaqSliceDefaultPrimary {
  /**
   * Title field in *Faq → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *Faq → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Primary content in *Faq → Items*
 */
export interface FaqSliceDefaultItem {
  /**
   * Title field in *Faq → Items*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *Faq → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: faq.items[].content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;
}

/**
 * Default variation for Faq Slice
 *
 * - **API ID**: `default`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FaqSliceDefaultPrimary>,
  Simplify<FaqSliceDefaultItem>
>;

/**
 * Slice variation for *Faq*
 */
type FaqSliceVariation = FaqSliceDefault;

/**
 * Faq Shared Slice
 *
 * - **API ID**: `faq`
 * - **Description**: Faq
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FaqSlice = prismic.SharedSlice<"faq", FaqSliceVariation>;

/**
 * Primary content in *Relationship → Primary*
 */
export interface RelationshipSliceDefaultPrimary {
  /**
   * Title field in *Relationship → Primary*
   *
   * - **Field Type**: Title
   * - **Placeholder**: *None*
   * - **API ID Path**: relationship.primary.title
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  title: prismic.TitleField;

  /**
   * Content field in *Relationship → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: relationship.primary.content
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  content: prismic.RichTextField;

  /**
   * Type field in *Relationship → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: relationship.primary.type
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  type: prismic.SelectField<"Conferences" | "Sponsors">;
}

/**
 * Default variation for Relationship Slice
 *
 * - **API ID**: `default`
 * - **Description**: Sections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelationshipSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RelationshipSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Relationship*
 */
type RelationshipSliceVariation = RelationshipSliceDefault;

/**
 * Relationship Shared Slice
 *
 * - **API ID**: `relationship`
 * - **Description**: Sections
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RelationshipSlice = prismic.SharedSlice<
  "relationship",
  RelationshipSliceVariation
>;

/**
 * Primary content in *Social → Items*
 */
export interface SocialSliceDefaultItem {
  /**
   * Name field in *Social → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social.items[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Social → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: social.items[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Acessibility field in *Social → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: social.items[].a11y
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  a11y: prismic.KeyTextField;

  /**
   * Visibility field in *Social → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: social.items[].active
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  active: prismic.BooleanField;
}

/**
 * Default variation for Social Slice
 *
 * - **API ID**: `default`
 * - **Description**: Social
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<SocialSliceDefaultItem>
>;

/**
 * Slice variation for *Social*
 */
type SocialSliceVariation = SocialSliceDefault;

/**
 * Social Shared Slice
 *
 * - **API ID**: `social`
 * - **Description**: Social
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SocialSlice = prismic.SharedSlice<"social", SocialSliceVariation>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ConferenceDocument,
      ConferenceDocumentData,
      HomeDocument,
      HomeDocumentData,
      NavigationDocument,
      NavigationDocumentData,
      PageDocument,
      PageDocumentData,
      SettingsDocument,
      SettingsDocumentData,
      SponsorDocument,
      SponsorDocumentData,
      AllDocumentTypes,
      CallToActionSlice,
      CallToActionSliceVariation,
      CallToActionSliceDefault,
      FaqSlice,
      FaqSliceVariation,
      FaqSliceDefault,
      RelationshipSlice,
      RelationshipSliceVariation,
      RelationshipSliceDefault,
      SocialSlice,
      SocialSliceVariation,
      SocialSliceDefault,
    };
  }
}
