// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Faq from './Faq';
import Relationship from './Relationship';
import Social from './Social';

export {
	CallToAction,
	Faq,
	Relationship,
	Social,
};

export const components = {
	call_to_action: CallToAction,
	faq: Faq,
	relationship: Relationship,
	social: Social,
};
