// Code generated by Slice Machine. DO NOT EDIT.

import CallToAction from './CallToAction';
import Relationship from './Relationship';

export {
	CallToAction,
	Relationship,
};

export const components = {
	call_to_action: CallToAction,
	relationship: Relationship,
};
